import type { Metadata } from "next";
import { inter } from "@/utils/fonts";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Theme } from "@radix-ui/themes";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="scroll-smooth">
         <body className={`${inter.variable} antialiased`}>
            <Theme>
               <div className="bg-white relative pl-1.2 pr-1.2 sm:pl-1.8 sm:pr-1.8">
                  <Navbar />
                  {children}
               </div>
            </Theme>
         </body>
      </html>
   );
}
